// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  cta: dynamic(() => import("./Cta")),
  faq: dynamic(() => import("./Faq")),
  feature: dynamic(() => import("./Feature")),
  footer_block: dynamic(() => import("./FooterBlock")),
  hero: dynamic(() => import("./Hero")),
  lead_magnet: dynamic(() => import("./LeadMagnet")),
  video_testimonial: dynamic(() => import("./VideoTestimonial")),
};
